services:
  - type: web
    name: freia-flowise
    runtime: docker
    plan: starter
    region: oregon
    branch: codebase-cleaning
    dockerfilePath: Dockerfile.render
    dockerContext: .
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /api/v1/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: FORCE_OSS
        value: "true"
      - key: DATABASE_TYPE
        value: "postgres"
      - key: DATABASE_HOST
        value: "dpg-d2u0qtar433s73dresng-a.oregon-postgres.render.com"
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        value: "freia_postgres"
      - key: DATABASE_USER
        value: "freia_postgres_user"
      - key: DATABASE_PASSWORD
        value: "imFxMeDUgcEzDbZqF3mR0fBunZHump0"
      - key: APIKEY_PATH
        value: "/opt/render/project/.flowise"
      - key: SECRETKEY_PATH
        value: "/opt/render/project/.flowise"
      - key: LOG_PATH
        value: "/opt/render/project/.flowise/logs"
      - key: BLOB_STORAGE_PATH
        value: "/opt/render/project/.flowise/storage"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "info"
      - key: ADMIN_EMAIL
        value: "admin@freia.ai"
      - key: ADMIN_PASSWORD
        value: "Testing123!"
      - key: ADMIN_NAME
        value: "Admin"
      - key: DISABLE_FLOWISE_TELEMETRY
        value: "true"
      - key: SHOW_COMMUNITY_NODES
        value: "true"
      - key: CORS_ORIGINS
        value: "*"
      - key: IFRAME_ORIGINS
        value: "*"
      - key: FLOWISE_FILE_SIZE_LIMIT
        value: "50mb"
      - key: JWT_AUTH_TOKEN_SECRET
        value: "8abff6478e0d06383deaa42f486e27c0435e89a6ff35c391c343"
      - key: JWT_REFRESH_TOKEN_SECRET
        value: "ca7dec4d4701ece54b03789e3f43f6ff0a4a3b8036e2ab9f8"
      - key: FLOWISE_SECRETKEY_OVERWRITE
        value: "8abff6478e0d06383deaa42f486e27c0435e89a6ff35c391c343"
      - key: JWT_ISSUER
        value: "FREIA_FLOWISE"
      - key: JWT_AUDIENCE
        value: "FREIA_USERS"
      - key: JWT_TOKEN_EXPIRY_IN_MINUTES
        value: "360"
      - key: JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES
        value: "43200"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: NPM_CONFIG_AUDIT_LEVEL
        value: "moderate"
      - key: FLOWISE_USERNAME
        value: "nahuelbalsas199@gmail.com"
      - key: FLOWISE_PASSWORD
        value: "Testing123!"
      - key: RATE_LIMIT_ENABLE
        value: "true"
      - key: RATE_LIMIT_MAX
        value: "1000"
      - key: RATE_LIMIT_DURATION
        value: "1"
      - key: TOOL_FUNCTION_BUILTIN_DEP
        value: "crypto,fs"
      - key: TOOL_FUNCTION_EXTERNAL_DEP
        value: "moment,lodash"
      - key: EXECUTE_CHILD_PROCESS
        value: "true"
      - key: WASENDER_API_TOKEN
        value: "51807b69afb0e9b4f6bd2afce35342247e3de2aa0cca18b1a6390cb80aafdd35"
    disk:
      name: freia-data
      mountPath: /opt/render/project/.flowise
      sizeGB: 2

databases: []